### ISSUE TITLE
'Allure Report’ aborted due to exception

### ISSUE THREAD

**Issue by admizh** [allure-framework/allure-gradle#25]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request

#### Current behavior:
My jenkins jobs execution stuck (~12 hours) when performing report generation...

#### Environment:
| Allure version | 2.3.5 |
| --- | --- |
| Test framework | testng@6.11 |
| Generate report using | (jenkins) allure-plugin@2.24 |
|OS| Windows 10|
|Jenkins| catched in 2.75, Still reproduce in 2.85 | 
#### Stacktrace
```
09:26:34 ERROR: Step ‘Allure Report’ aborted due to exception: 
09:26:34 java.lang.InterruptedException
09:26:34 	at java.lang.ProcessImpl.waitFor(Unknown Source)
09:26:34 	at hudson.Proc$LocalProc.join(Proc.java:324)
09:26:34 	at hudson.Launcher$ProcStarter.join(Launcher.java:475)
09:26:34 	at ru.yandex.qatools.allure.jenkins.ReportBuilder.build(ReportBuilder.java:47)
09:26:34 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:287)
09:26:34 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:210)
09:26:34 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
09:26:34 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
09:26:34 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
09:26:34 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:682)
09:26:34 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
09:26:34 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:627)
09:26:34 	at hudson.model.Run.execute(Run.java:1749)
09:26:34 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
09:26:34 	at hudson.model.ResourceController.execute(ResourceController.java:97)
09:26:34 	at hudson.model.Executor.run(Executor.java:421)
09:26:34 Archiving artifacts
```

**Comment by eroshenkoam** [comment]
Why are you using jenkins + gradle-plugin instead jenkins-plugin?

**Comment by BlazerYang** [comment]
so do i, is there any solution yet?

**Comment by admizh** [comment]
@BlazerYang flowed to TeamCity :)
